import NextAuthProvider from '@/Providers/nextauth.provider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<NextAuthProvider>
			<html lang='en'>
				<body>{children}</body>
			</html>
		</NextAuthProvider>
	);
}
